### ISSUE TITLE
Знайти зображення котика

### ISSUE THREAD

**Issue by VikaSomuk** [VikaSomuk/Lest_projekt#1]

**Comment by TaniaZakorchemna** [comment]
https://www.google.com.ua/search?q=%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%BD%D1%8F+%D0%BA%D0%BE%D1%82%D0%B8%D0%BA%D0%B0&tbm=isch&source=iu&ictx=1&fir=Vf-4KysFKPPvIM%253A%252CFbOdLf8mTAg6sM%252C_&usg=AI4_-kTEJRkQpOvYFvDf_80KXbKxhnzkrw&sa=X&ved=2ahUKEwjS5deM28HeAhWOiqYKHW6JA_wQ9QEwAHoECAUQBA#imgdii=jzH27iKBRi8ccM:&imgrc=b38RWzYZ65WiqM:

**Comment by VikaSomuk** [comment]
![image](https://user-images.githubusercontent.com/44829478/48115833-d0123680-e26c-11e8-801f-b53682df50f2.png)

**Comment by TaniaZakorchemna** [comment]
![image](https://user-images.githubusercontent.com/44829487/48115863-eb7d4180-e26c-11e8-8306-ca816b5ad1e4.png)

**Comment by VikaSomuk** [comment]
![image](https://user-images.githubusercontent.com/44829478/48115893-018b0200-e26d-11e8-8bf0-afa68dda0969.png)
